import type { Metadata } from "next";
import { Lusitana, Inter } from "next/font/google";
import "./globals.css";

// Configure Lusitana font from Google Fonts
const lusitana = Lusitana({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lusitana",
});

// Configure Inter font from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lusitana.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
